name: Build NDK

on:
  workflow_dispatch:
    inputs:
      langs:
        description: 'Additional languages - comma separated'
        default: 'fortran'
        required: true
        type: string
      ndk:
        description: 'Specify NDK version to check out to (from: https://android.googlesource.com/platform/manifest/+refs, e.g. "ndk-r26-release"'
        required: false
        type: string
      release:
        description: 'Create release'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Add universe repository for Python 2.7
      run: sudo apt-add-repository universe
    - name: Install packages and set Python 2.7 as default Python
      run: |
        sudo apt-get update && \
        sudo apt-get upgrade -y && \
        sudo apt-get install -y git repo make gcc g++ m4 texinfo bison flex python2-minimal && \
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1 && \
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
    - name: Setup git
      run: |
        git config --global user.name "John Smith" && \
        git config --global user.email "john.smith@gmail.com"
    - name: Repo init
      run: repo init -u https://android.googlesource.com/platform/manifest -b gcc --depth 1
    - name: Repo sync
      run: repo sync -c
    - name: Checkout NDK
      if: github.event.inputs.ndk != ''
      run: |
        NDK=$(echo "${{ inputs.ndk }}" | tr -d ' ') && \
        echo "Checking out NDK: $NDK" && \
        repo forall -c git checkout $NDK
    - name: Add additional languages
      run: |
        LANGS=$(echo "${{ inputs.langs }}" | tr -d ' ') && \
        sed -i -e "s/ENABLE_LANGUAGES=\"c,c++\"/ENABLE_LANGUAGES=\"c,c++,$LANGS\"/g" toolchain/gcc/build-gcc.sh
    - name: Check contents
      run: cat toolchain/gcc/build-gcc.sh | grep ENABLE_LANGUAGES
    - name: Build
      run: |
        cd toolchain/gcc && \
        ./build.py -h
